---
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        alias: toml

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.5.0
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-format
        alias: ruff
      - id: ruff-check
        alias: ruff
