---
# For use with pre-commit.
# See usage instructions at http://pre-commit.com

- id: ansible-sign
  name: Ansible-sign
  description: This hook runs ansible-sign.
  entry: ansible-sign project gpg-sign .
  language: python
  pass_filenames: false
  always_run: true
