---
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
  commands:
    - pip install --user tox
    - python3 -m tox -e docs
python:
  install:
    - method: pip
      path: tox
    - method: pip
      path: .
      extra_requirements:
        - docs
submodules:
  include: all
  recursive: true
