---
name: tox

on:
  merge_group:
    branches:
      - "main"
  push:
    branches:
      - "main"
      - "releases/**"
      - "stable/**"
  pull_request:
    branches:
      - "main"
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tox:
    uses: ansible/team-devtools/.github/workflows/tox.yml@main
    with:
      jobs_producing_coverage: 6
      other_names: |
        docs
        lint
        pkg
